### ISSUE TITLE
access-details for apps that use sql or sqlite

### ISSUE THREAD

**Issue by mgiljum** [htpcBeginner/AtoMiC-ToolKit#116]
Current method in grabbing the user/pass/port is via grep on the apps settings XML file, .config, etc. 

However some apps use sql or slqite for their settings where a simple grep isn't enough, and a DB query would be necessary.

Problem is that every db will have different tables/column names, so one viable option to do that might be setting separate queries per each app to a var in `appname-constants` and calling it in a `db-app-access` include.

**Comment by TommyE123** [comment]
Yes your right, We have a few different ways we need to extract the info from different types of files. If your happy to look at this i'd be very grateful and i'll run with whatever you feel is required. I'm thinking could we have maybe a APPSETTINGSTYPE constant and then further constants, if it needs DB tablename and column? Then we just need to change the main controller scripts to work with these rather than having to create an access details script for each application? Not sure i've really thought this through properly though!!

**Comment by mgiljum** [comment]
That's probably the best way of going about it, makes less work in the future when you're adding new features. Otherwise you'd have to point their menus to different includes for getting the db type settings.
