### ISSUE TITLE
new version of Ubooquity

### ISSUE THREAD

**Issue by lbesnard** [htpcBeginner/AtoMiC-ToolKit#179]
The new version of Ubooquity (> 2.0) seems to have different parameters

https://github.com/htpcBeginner/AtoMiC-ToolKit/blob/master/ubooquity/ubooquity.service#L8

should be 
```
ExecStart=/usr/bin/java -jar Ubooquity.jar -headless -remoteadmin
```

Also I think that the /opt/ubooquity folder needs to be wiped out before the update.

Thanks for an amazing tool though

**Comment by TommyE123** [comment]
Thanks for bringing this to my attention. 

I've changed over the Execstart line for now as a quick win and will investigate the folder wipe as well later.

**Comment by thagoat** [comment]
Also note when upgrading from 1.X to 2.X the admin port moves to 2203/admin. This fixes the "You are not authorized to access any files on this server" error.
I bashed my head against the wall for a few weeks over this!

**Comment by startrekin** [comment]
Haha. Thanks for he Atomic guide, first of all! Working through it now with Ubooquity. Spent a bit of time trying to figure out Ubooquity/admin. The comment from thegoat saved me: port 2203 vs. 2202 (as it seemed to have been in previous versions?).

**Comment by TommyE123** [comment]
Hi thanks again for bringing this to my attention. I've puts some fixes in and hopefully made it slightly clearer there's 2 ports to use. I've also made some fixes around backups and a couple of other access detail fixes as the config file structure changed. I'm gonna leave the fact it needs a reinstall if you update from a lower version as its been a while now since that breaking change they made was put in. I also don't want to wipe it every go when most of the time we don't need to.

If anyone has anymore issues or suggestions just let me know and i'll be happy to help.
