### ISSUE TITLE
Issues with getting ombi working with reverse proxy (nginx).

### ISSUE THREAD

**Issue by josharmour** [htpcBeginner/AtoMiC-ToolKit#230]
## The problem
I'm trying to configure external access to all my services via muximux and nginx.  When navigating to port 80 on my wan IP from outside my network I simply get the landing page for nginx.  When I try to move to any other subdirectory like /muximux I get forbidden.

### I'm seeing this behaviour on: 
Install that has sab, plex, plexpy, sonarr, muximux, webmin, ombi, and couchpotato.

### Link to install logs
https://gist.github.com/josharmour/e16083cc8fd6a8d3d1cc69ba702e1e69
Note, there are two locations that have what appear to be nginx files: 

$ ls /var/www/muximux/
browserconfig.xml  Dockerfile   less           README.md                 test
cache              favicon.ico  LICENSE        robots.txt                vendor
combineify.php     fonts        login.php      scss
composer.json      images       manifest.json  secret.txt
CONTRIBUTORS.md    index.php    muximux.log    settings.ini.php
css                js           muximux.php    settings.ini.php-example

$ ls /usr/share/nginx/html/
50x.html  index.html

### I'm not a dummy, so I've checked these!
- I'm using the latest version of AtoMiC-ToolKit. 
- All my Linux distro packages are up to date and I don't see any errors while updating.
- I've checked there are no current open issues relating to my problem!

**Comment by josharmour** [comment]
I did try to drop a symbolic link to my actual muximux install in the nginx directory (or so I thought)  by running this command.

sudo ln -s /var/www/muximux /usr/share/nginx/html/muximux

However that didn't work when trying to hit my public ip:/muximux - I got permission denied.

Also I think maybe that other directory /var/www/ is an nginx install?

**Comment by josharmour** [comment]
I got /muximux to work by changing my server_name to my dyndns domain in /etc/nginx/nginx.conf

So the main reason I opened this is now resolved.  However I still can't navigate to any of the services defined in muximux.  Things like sabnzbd and ombi are not showing.

I think that I can solve this by creating the 'server blocks' in /etc/nginx/sites-available/AtoMiC-ToolKit-configured-sites

I would be creating entries in there for each of the services like so?

 location /couchpotato {
    proxy_pass http://127.0.0.1:5050;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

However I'm not sure if this is right?  Also, I'd still need to update muximux to now use the dyndns name that I've defined instead of the local address.  Am I on the right track?

**Comment by josharmour** [comment]
I updated the title to be more accurate of the current evolving issue.

I can view muximux from outside my network but I can't view /ombi by itself or via muximux.

I think it may be related to the base url setting in ombi however I'm not sure if I have it defined correctly in sites-enabled config.

**Comment by TommyE123** [comment]
Hi @josharmour,

Sorry no one has got back to you sooner. Unfortunately this is something the Toolkit doesn't currently help configure and I don't have much experience in this area yet. We are certainly looking to get this working in future and have already started on the scripts and configs. As a stab in the dark I would hope to have these in place by end of Jan however that's if nothing else goes wrong in the meantime!

@nemchik has some experience getting this working and might be able to help, or is there anyone else?!?

I would strongly advise joining the [Gitter](https://gitter.im/htpcBeginner/AtoMiC-ToolKit) chat room and posting in there as well to see if anyone can help.

Also if you've not seen it already you can vote for future new features on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit).

**Comment by nemchik** [comment]
While this issue is not actually an issue with Atomic, but rather just a question about how to configure nginx.

I've made a PR https://github.com/nemchik/AtoMiC-ToolKit/commit/82a0646e0150f2bbb75e1d21a16e4231425f93fe for initial testing but haven't had much time to follow up with it. The PR shows you all the differences in the proposed files vs the current files.

Just for a more direct answer to your question, if you have a look here https://github.com/nemchik/AtoMiC-ToolKit/blob/82a0646e0150f2bbb75e1d21a16e4231425f93fe/utils/nginx/AtoMiC-ToolKit-configured-sites you can see one of the proposed files by itself. You could very easily copy this file and replace your existing `/etc/nginx/sites-available/AtoMiC-ToolKit-configured-sites` file but be sure to have a look at line 6 `server_name  IPADDRESS 0.0.0.0;` as this is where you'll want to put your DDNS. Mine reads like this and works very well both internally and externally `  server_name  ddns.mydomain.com 192.168.1.21 127.0.0.1 0.0.0.0;`. You'll notice I have my DDNS, internal IP, 127.0.0.1, and 0.0.0.0 in there and they all work together. You'll also want to look at line 99 `fastcgi_pass unix:/var/run/php/FPMVERSION.sock;` and be sure to replace `FPMVERSION` with the path to your PHP fpm.sock file (which depends on which version of PHP you have). Atomic by default installs PHP 7.1 so you should be able to replace `FPMVERSION` with `php7.1-fpm` and be good to go. After doing both of those things you will want to add a location block that looks like this
```
  location /couchpotato/ {
    proxy_pass http://127.0.0.1:5050;
  }
```
On line 71 I have `proxy_pass http://127.0.0.1:5000;` which is actually the port for Ombi v3. If you're using Ombi v2 (which is what Atomic includes) you'll want to change the port from 5000 to 3579.

After getting that first file setup you will want to locate `/etc/nginx/nginx.conf` and have a look at https://github.com/nemchik/AtoMiC-ToolKit/blob/82a0646e0150f2bbb75e1d21a16e4231425f93fe/utils/nginx/nginx.conf but in this case you can copy the entire file with no changes and it should work without issue.

Once you're done editing both of those files you'll need to run `sudo systemctl reload nginx.service` and then try visiting your DDNS or internal IP address pages and see if everything works.

I would love to know how it all works out for you. If you can tell us what issues you have I can make changes or additions to my PR which will hopefully get added before the next version of Atomic releases.

**Comment by TommyE123** [comment]
Thanks @nemchik

As this technically isn't an ATK issue im going to close this but we can continue the conversation if you require anymore help.

Thanks
Tom

**Comment by nemchik** [comment]
Copying from gitter:

@josharmour i should also mention that for each of those services you NEED to go set the base url to /folder/ (ex: /ombi/) before trying to access them without using their ports. so navigate to http://your.ip:port/ and get logged in and configure the settings for base url. i would love to find a way around this in the future but i forgot all about it. @TommyE123 FYI when testing
after you set the port for ombi for example you should be able to visit both http://your.ip:port/ombi and http://your.ip/ombi and both will work
and after that you can visit http://your.ddns/ombi as well

**Comment by josharmour** [comment]
Thanks, this worked great!  Thanks for the help.
