### ISSUE TITLE
Docker for everything

### ISSUE THREAD

**Issue by lordraiden** [htpcBeginner/AtoMiC-ToolKit#247]
It's in the roadmap the idea of using docker for everything ATK installs? 
Almost everything and more ATK use is available as a container in https://tools.linuxserver.io/dockers
And the management could be done with Portainer.
It could be even a SO based on Rancher OS.
Backups, maintenance, updates, everything would be easier and cleaner.
I am willing to contribute with money if this goes through a crowfunding campaign

**Comment by nemchik** [comment]
By the sounds of it, everything you want already exists. ATK doesn't need to be involved. ATK of aimed at people who don't want to (or can't) use docker. ATK supports hardware that docker would struggle on (or just flat out not exist on). If this a actually were to be added, ATK would have to maintain everything it currently does PLUS take separate docker methods into consideration for each app. This seems like a lot of duplicated effort.

+1 vote to close this issue.

**Comment by lordraiden** [comment]
What? lol
ATK would be much easier to maintain if it where based on Docker based on images already provided by the community.
What hw won't be supported by Docker that is supported by ATK?

I think you don't know what are you talking about.

**Comment by lordraiden** [comment]
Probably you don't even know what Docker is but since you mentioned that the docker version will be more limited... You can even run Linux containers on windows using Docker. Now ATK only runs in certain Linux distros.

**Comment by nemchik** [comment]
No need to be rude. I know what docker is, and how it works, and the difference in performance running something in a docker container vs directly on a system. I'll restate that everything you are asking for is already available and you personally outlined exactly how to do it all without having a tool like ATK do it for you.

ATK isn't a project about using docker, it's a project about installing things directly to a system. And even if ATK were to be switched too 100% docker, the method by which you install docker and the specifics about where you store information would differ from Windows to Linux. ATK offers best practices and quick/easy setup directly to systems that might otherwise not be able to run docker (whether for performance, or just because docker itself might not be available for a specific OS/architecture).

System requirements aside, I'll say again that you personally already provided all of the information needed to do everything ATK does with docker, and it's not like you're reinventing the wheel or have some complex installation process. I would dare to say your desired outcome is just as easy as using ATK. So why are you asking the maintainers of ATK to uproot the whole project in favor of docker?

**Comment by nemchik** [comment]
https://feathub.com/htpcBeginner/AtoMiC-ToolKit/+19

**Comment by nemchik** [comment]
Oh the irony.

Mere weeks after this conversation took place Tommy and I took up the task of making a brand new project in the spirit of ATK, but done with docker.

https://dockstarter.com/

This new project has grown larger than ATK, in that it has more apps, an active community of support.

I'm only just now looking back at this thread due to a notification about another comment here in this repo. Anyway it would have been a nightmare to evolve ATK into a docker based install system. Making a new project was the way to go. It was announced in the readme here in this repo, but I don't think we did a lot of issue triage to find closed issues and direct people to the new project. Anyway, I hope you've been able to get something setup to your liking, but if not feel free to check out DockSTARTer.
