### ISSUE TITLE
headphones is broken it isn't accessible from the external ip.

### ISSUE THREAD

**Issue by myusuf3** [htpcBeginner/AtoMiC-ToolKit#27]

**Comment by myusuf3** [comment]
I am able to curl it from `http://localhost:8181/home` locally on the box though.

**Comment by ZaLiTHkA** [comment]
I don't see this as a problem with the installation script; this is a pretty typical way to configure network related systems.. The idea of "most restrictive first" ensures that there's limited access until you've configured all the security options correctly.

There's a bit more information on this point [here](https://github.com/rembo10/headphones/issues/2288) and [here](https://github.com/rembo10/headphones/wiki/Usage-guide#web-interface). Hope that helps a bit.. :)

**Comment by ZaLiTHkA** [comment]
I'm not saying everybody follows this logic with their projects, but the issue and wiki page I linked you to show that the maintainers of Headphones do.

Maybe there's a way this script could prompt the user for whether or not to enable network access and modify it accordingly. I've never used Headphones before though, so I'm not familiar with it's configuration.

I'm at work at the moment though, so I don't have time to look at it right now.. Unless someone beats me to it, I'll see what I can come up with this evening.

**Comment by ZaLiTHkA** [comment]
So, quick hack.. Turns out the `config.ini` file is only written to disk when settings are saved from within the interface, however they're done in a non-destructive way. :) Try [this fork](/ZaLiTHkA/AtoMiC-ToolKit/tree/feature-headpones-network-access-prompt) and see if that helps you.

@htpcBeginner, not sure if you want to include this in the main repo? Feel free to pull changes from my branch if you want, I'll leave that choice up to you.

**Comment by myusuf3** [comment]
Awesome will give it a shot!

**Comment by carrigan98** [comment]
If @ZaLiTHkA  fork doesn't work, try changing to the local IP of the server, ex `192.168.1.110`. Perhaps change the fork to identify the computers IP address?

**Comment by htpcBeginner** [comment]
Added a fix for this in dev branch.
